title: radiolevity Web Design
email: radiolevity.design@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Friendly neighborhood web design
baseurl: "" 
url: "https://radiolevity.com"
github_username:  radiolevity

# Build settings
markdown: kramdown

# plugins
plugins:

collections:
  - forums
  - currently

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  